name: Create Release

on:
  push:
    branches:
      - main

jobs:
    create-docker-image:
        runs-on: ubuntu-latest

        steps:

        - name: Clone vantage6 repository
          uses: actions/checkout@v4
          with:
            repository: vantage6/vantage6
            ref: release/5.0
            path: vantage6
        
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Login to Docker registry
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Run Makefile Rule
          run: docker build -t hcadavidescience/v6-sessions-diagnostics .
          
        - name: Push Docker image
          run: |
            docker push hcadavidescience/v6-sessions-diagnostics
